language: c

branches:
    only:
        - master
env:
	global:
        - DOCKER_REPO=zephyr
        - DOCKER_ACC=nashif

build:
    ci:
        - cd shippable
        - docker build -t nashif/zephyr:$BRANCH.$BUILD_NUMBER .
    post_ci:
    	- docker push nashif/zephyr:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: DH-Integration
      type: docker
