# Copyright (c) 2020 Linaro Limited.
# SPDX-License-Identifier: Apache-2.0

# Git Hub workflow to build docker container on PR to make sure
# any changes to the container still produce a work container

name: Docker Image CI

on: [pull_request]

env:
  DOCKER_USER: zephyrprojectrtos
  DOCKER_REPO: ci

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        cd shippable
        df -h
        # remove a few things to free up space
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        docker build . --file Dockerfile --tag docker.io/${DOCKER_USER}/${DOCKER_REPO}:${{ github.sha }}
